ca_cert_path:
client_id:
username: 
password:
host: tcp://mqtt.eclipse.org:1883
use_tls: false
reconnect: true
reconnect_interval: 10
reconnect_retries: 0
ping_timeout: 2
connect_timeout: 4
keep_alive: 5